### ISSUE TITLE
SyntaxError: Unexpected token >

### ISSUE THREAD

**Issue by Gutbuket** [ptarmiganlabs/butler-sos#4]
I get the below when trying to run. Have I just done something stupid or missed a step somewhere?

node --version is v0.10.30 running on CentOS.

/root/butler/butler/butler-sos.js:164
    .then(err => {
               ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

**Comment by Gutbuket** [comment]
Fixed by changing node.js to 8.11.1

**Comment by mountaindude** [comment]
Nice find!
