### ISSUE TITLE
TypeError: Cannot read property 'committed' of undefined

### ISSUE THREAD

**Issue by Gutbuket** [ptarmiganlabs/butler-sos#6]
When running node butler.node.js I receive this error:
TypeError: Cannot read property 'committed' of undefined (full output below)

I am running as root, 
node.js 8.11.0, 8.11.0 and 8.11.2 tested, with the same error.

[root@qlikserver1 butler]# node butler-sos.js
2018-06-26T03:26:05.783Z - info: Starting Butler SOS
2018-06-26T03:26:05.785Z - info: Log level is: verbose
2018-06-26T03:26:05.828Z - info: Connected to Influx database.
2018-06-26T03:26:10.786Z - verbose: Event started: Statistics collection
2018-06-26T03:26:10.787Z - verbose: Getting stats for server: QlikServer2
2018-06-26T03:26:10.831Z - verbose: Received ok response from QlikServer2
/root/butler/butler/butler-sos.js:199
    body.mem.committed.toString()
             ^

TypeError: Cannot read property 'committed' of undefined
    at postHealthToMQTT (/root/butler/butler/butler-sos.js:199:14)
    at Request._callback (/root/butler/butler/butler-sos.js:308:11)
    at Request.self.callback (/root/butler/butler/node_modules/request/request.js:186:22)
    at Request.emit (events.js:180:13)
    at Request.<anonymous> (/root/butler/butler/node_modules/request/request.js:1163:10)
    at Request.emit (events.js:180:13)
    at IncomingMessage.<anonymous> (/root/butler/butler/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:272:13)
    at IncomingMessage.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1106:12)

**Comment by mountaindude** [comment]
For future questions - these kind of errors are usually due to misconfiguration of paths. 
The service cannot - for one reason or another - find the config file where all settings are defined. 
It could be an incorrect path, that the Docker image is executed using a user without permissions to the config directory, or various other reasons. 

Closing ticket for now. Please reopen if needed.
