### ISSUE TITLE
InfluxDB v1 is broken in 10.0.0

### ISSUE THREAD

**Issue by mountaindude** [ptarmiganlabs/butler-sos#814]
### What version of Butler SOS are you using?

10.0.0

### Which version(s) of Butler SOS work for you?

9.6.1

### What version of Node.js are you using? Not applicable if you use the standalone version of Butler SOS.

-

### What operating system are you using?

-

### What CPU architecture are you using?

-

### What Qlik Sense versions are you using?

-

### Describe the Bug

```
2024-06-04T07:51:35.690Z error: HEALTH METRICS: Error saving health data to InfluxDB! Error: Extraneous tags detected for writing InfluxDB point in senseops.sense_server: `server_group`, `serverLocation`, `server_type`, `serverBrand`.
    at Schema.checkTags (/home/goran/code/butler-sos/node_modules/influx/lib/src/schema.js:83:19)
    at InfluxDB.parsePoint (/home/goran/code/butler-sos/node_modules/influx/lib/src/index.js:919:43)
    at /home/goran/code/butler-sos/node_modules/influx/lib/src/index.js:834:89
    at Array.forEach (<anonymous>)
    at InfluxDB.writePoints (/home/goran/code/butler-sos/node_modules/influx/lib/src/index.js:833:16)
    at Object.postHealthMetricsToInfluxdb (/home/goran/code/butler-sos/src/lib/post-to
```

Seems InfluxDB v1 support broken when v2 support was added.

### Expected Behavior

Both InfluxDB v1 and v2 should work with Butler SOS

### To Reproduce

-

**Comment by mountaindude** [comment]
False alarm.

The config file used was not correct wrt tags defined for the servers in general (and thus should be present for all servers), and what tags were actually provided for each server.

Not a bug per se thus, but startup verification of the config file can be better here.
Open a separate ticket about this.
