### ISSUE TITLE
Start getting app names error

### ISSUE THREAD

**Issue by chevcheli0s** [ptarmiganlabs/butler-sos#943]
### What version of Butler SOS are you using?

11.0.3

### What version of Node.js are you using? Not applicable if you use the standalone version of Butler SOS.

18.5.0

### What command did you use to start Butler SOS?

./butler-sos

### What operating system are you using?

Debian 12

### What CPU architecture are you using?

x86_64

### What Qlik Sense versions are you using?

2024 Feb sp7

### Describe the Bug

With 7.0.3 all was fine. After upgrade to 11.0.3 get error when enableAppNameExtract: true 
```
nov 06 12:51:56 tst-vm-butler butler-sos[249523]: 2024-11-06T09:51:56.745Z verbose: APP NAMES: Start getting app names from repository db
nov 06 12:51:56 tst-vm-butler butler-sos[249523]: pkg/prelude/bootstrap.js:438
nov 06 12:51:56 tst-vm-butler butler-sos[249523]:   if (error) throw error;
nov 06 12:51:56 tst-vm-butler butler-sos[249523]:              ^
nov 06 12:51:56 tst-vm-butler butler-sos[249523]: Error: File '/**/butler-sos/config/certificate/test/client.pem' was not included into executable at compilation stage. Please recompile adding it as asset or script.
nov 06 12:51:56 tst-vm-butler butler-sos[249523]:     at error_ENOENT (pkg/prelude/bootstrap.js:657:19)
nov 06 12:51:56 tst-vm-butler butler-sos[249523]:     at readFileFromSnapshot (pkg/prelude/bootstrap.js:1046:29)
nov 06 12:51:56 tst-vm-butler butler-sos[249523]:     at Object.readFileSync (pkg/prelude/bootstrap.js:1094:18)
nov 06 12:51:56 tst-vm-butler butler-sos[249523]:     at new zqt (/snapshot/butler-sos/build.cjs:1009:16097)
nov 06 12:51:56 tst-vm-butler butler-sos[249523]:     at bjt (/snapshot/butler-sos/build.cjs:1009:26783)
nov 06 12:51:56 tst-vm-butler butler-sos[249523]:     at Timeout._onTimeout (/snapshot/butler-sos/build.cjs:1009:27359)
nov 06 12:51:56 tst-vm-butler butler-sos[249523]:     at listOnTimeout (node:internal/timers:564:17)
nov 06 12:51:56 tst-vm-butler butler-sos[249523]:     at process.processTimers (node:internal/timers:507:7) {
nov 06 12:51:56 tst-vm-butler butler-sos[249523]:   errno: -2,
nov 06 12:51:56 tst-vm-butler butler-sos[249523]:   code: 'ENOENT',
nov 06 12:51:56 tst-vm-butler butler-sos[249523]:   path: '/snapshot/butler-sos/config/certificate/test/client.pem',
nov 06 12:51:56 tst-vm-butler butler-sos[249523]:   pkg: true
nov 06 12:51:56 tst-vm-butler butler-sos[249523]: }
nov 06 12:51:56 tst-vm-butler butler-sos[249523]: Node.js v18.5.0
nov 06 12:51:56 tst-vm-butler systemd[1]: butler-sos-test.service: Main process exited, code=exited, status=1/FAILURE
nov 06 12:51:56 tst-vm-butler systemd[1]: butler-sos-test.service: Failed with result 'exit-code'.
nov 06 12:51:56 tst-vm-butler systemd[1]: butler-sos-test.service: Consumed 3.105s CPU time.
nov 06 12:51:57 tst-vm-butler systemd[1]: butler-sos-test.service: Scheduled restart job, restart counter is at 1.
nov 06 12:51:57 tst-vm-butler systemd[1]: Stopped Butler-SOS.
nov 06 12:51:57 tst-vm-butler systemd[1]: butler-sos-test.service: Consumed 3.105s CPU time.
nov 06 12:51:57 tst-vm-butler systemd[1]: Started Butler-SOS.
```

**Comment by mountaindude** [comment]
I've tested this with version 11.1.0 and cannot reproduce it. There were lots of changes in that release, might be that fixing this bug never made it into the release notes.
